# Generated by Django 5.0 on 2025-11-30 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_task_due', models.BooleanField(default=True)),
                ('email_task_completed', models.BooleanField(default=True)),
                ('email_comment_added', models.BooleanField(default=True)),
                ('email_team_invitation', models.BooleanField(default=True)),
                ('email_mention', models.BooleanField(default=True)),
                ('email_payment_reminder', models.BooleanField(default=True)),
                ('email_subscription_updates', models.BooleanField(default=True)),
                ('inapp_task_assigned', models.BooleanField(default=True)),
                ('inapp_task_due', models.BooleanField(default=True)),
                ('inapp_task_completed', models.BooleanField(default=True)),
                ('inapp_comment_added', models.BooleanField(default=True)),
                ('inapp_team_invitation', models.BooleanField(default=True)),
                ('inapp_mention', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('TASK_DUE', 'Task Due Soon'), ('TASK_OVERDUE', 'Task Overdue'), ('TASK_COMPLETED', 'Task Completed'), ('COMMENT_ADDED', 'Comment Added'), ('TEAM_INVITATION', 'Team Invitation'), ('TENANT_INVITATION', 'Tenant Invitation'), ('MENTION', 'Mentioned in Comment'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('PAYMENT_FAILED', 'Payment Failed'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('SYSTEM', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
